root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/worker ./cmd/worker/main.go"
bin = "./tmp/worker"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "frontend"]
log = "build-worker-errors.log"
delay = 1000 # ms

[log]
time = true

[misc]
clean_on_exit = true
