# air (Go 热重载) 配置文件
# 根目录，相对于此文件的位置
root = "."
tmp_dir = "tmp" # 临时构建目录

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "tmp/api"
  full_bin = "tmp/api"
  delay = 1000

[log]
  color = true
  time = true

[watch]
  dir = "."
  # 要监视的文件扩展名
  include_ext = ["go", "tpl", "tmpl", "html"]
  # 要监视的目录
  include_dir = ["cmd/api", "internal"]
  # 要忽略的目录
  exclude_dir = ["tmp", "vendor", "node_modules","assets"]
  # 当这些文件/目录变化时触发重新构建
  include_file = []
  # 忽略这些文件
  exclude_file = []

[misc]
  # 第一次构建失败时退出
  fatal = true

[screen]
  # 清理屏幕
  clear_on_rebuild = true