global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app-services'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: network
            values: ['phresume_app-network']

    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: (api|worker)
        action: keep
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: api
        target_label: __address__
        replacement: api:8080
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        regex: worker
        target_label: __address__
        replacement: worker:9100
      - target_label: __metrics_path__
        replacement: /metrics
